log4j.rootCategory=DEBUG,stdout

#lembrando a ordem: DEBUG \u2013 ALL \u2013 WARN \u2013 ERROR \u2013 FATAL
log4j.category.lopes=ALL
log4j.category.org.springframework.jdbc=TRACE
#### O primeiro appender escreve no console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
### Pattern que mostra o nome do arquivo e numero da linha, porem sem data e hora
log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n
#### O segundo appender escreve em um arquivo e faz um bkp ao atingir o max
log4j.appender.stdout =org.apache.log4j.RollingFileAppender
#log4j.appender.fileOut.File=D:/PortalCorretor/YMViaCorretor/logs/ViaCorretor.log
log4j.appender.stdout.File=/u/dadosapp/logs/CotacaoMulti/logs.log
### Controla o tamanho maximo do arquivo
log4j.appender.stdout.MaxFileSize=4000KB
### Faz backup dos arquivos de log (apenas 5)
log4j.appender.stdout.MaxBackupIndex=5
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#####este formato esta em ingles: 2011-04-24 e imprime o nro da linha L
log4j.appender.stdout.layout.ConversionPattern=%d [%t] %5p %c:%L - %m%n
