#log4jConfigLocation=file:///D:/PortalCorretor/CotacaoAuto/properties/log4j.properties
#log4jConfigLocation=file:/Users/wagnermachadofilho/Development/git/sompo-cotacaomulti/CotacaoMulti/src/log4j.properties
#properties.folder=D:/PortalCorretor/CotacaoAuto/properties
properties.folder=/u/dadosapp/config/CotacaoMulti

#############################################################################

#Envio de e-mail para Operação SISCOTA - Contas Internacionais
email.operacao.siscota.assunto=Operacao Siscota - Contas Internacionais [Usuario: ID_USUARIO]
email.operacao.siscota.mensagem=Segue as informações para análise: Usuário ID_USUARIO - CNPJ NUM_CNPJ
email.sompo.origem=noreply@sompo.com.br
email.operacao.siscota=lsandrade@sompo.com.br
#email.operacao.siscota=aasousa@sompo.com.br
#negociosinternacionais@sompo.com.br
#DEV
#email.url.servico.envio=http://10.110.0.25:7080/EmailWS

#HOMOG
email.url.servico.envio=https://serviceshml.sompo.com.br/EmailWS

#PROD
#email.url.servico.envio=https://services.sompo.com.br/EmailWS



######################SUSEP-HISTORICO-API##############
#QA
susep.hist.api.url=https://portalwebhml.sompo.com.br/susep-historico-api
susep.hist.api.recurso=/susep/v1/

#PROD
#susep.hist.api.url=https://portalweb.sompo.com.br/susep-historico-api
#susep.hist.api.recurso=/susep/v1/

